exclude:
  - node_modules
  - script

sass:
  style: compressed

# theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/junian/jekyll-linkinbio"
  
title: Jekyll Theme LinkinBio
description: Jekyll-LinkinBio is a Jekyll theme for GitHub Pages
keywords: your name, industry, and specialties
author:
  name: junian

links:
  - text: Google
    url: https://google.com
    icon: littlelink
    style: default
    alt: Google

